### ISSUE TITLE
[crash] Crash when installing Button (Radix ui only)

### ISSUE THREAD

**Issue by GunniBusch** [WarningImHack3r/intellij-shadcn-plugin#30]
### What is the issue?

Crash after downloading button (the radix ui was not installed so there lies the issue)

```
 java.lang.ClassCastException: class com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor cannot be cast to class java.util.concurrent.ScheduledExecutorService (com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor is in unnamed module of loader com.intellij.util.lang.PathClassLoader @4c75cab9; java.util.concurrent.ScheduledExecutorService is in module java.base of loader 'bootstrap')
```

### What are the steps to reproduce this issue?

Install button

### What were you expecting to happen?

Installing button worked but installing radix ui not

### Paste any relevant logs, error output, etc.

```shell
java.lang.ClassCastException: class com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor cannot be cast to class java.util.concurrent.ScheduledExecutorService (com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor is in unnamed module of loader com.intellij.util.lang.PathClassLoader @4c75cab9; java.util.concurrent.ScheduledExecutorService is in module java.base of loader 'bootstrap')
	at com.github.warningimhack3r.intellijshadcnplugin.notifications.NotificationManager.sendNotification(NotificationManager.kt:37)
	at com.github.warningimhack3r.intellijshadcnplugin.notifications.NotificationManager.sendNotificationAn

<TRIMMED STACKTRACE>
```

### What OS are you experiencing the problem on?

macOS

### Additional platform information

Build version: WebStorm 2023.3.6 Build: #WS-233.15026.13 March 21, 2024
JRE: 17.0.10+1-b1087.23, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.23, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.3.1 (aarch64)

=== Plugins ===
Custom plugins: [Prisma ORM (233.13135.65), Space (233.15026.16), .env files support (2024.1), shadcn/ui Components Manager (0.7.6), GitHub Copilot (1.5.1.5285), React Buddy (233.13135.65)]
Disabled plugins:[]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Thanks for reporting! I'm looking into it, sorry for the inconvenience
