### ISSUE TITLE
Got the error Multiple Project Detected, not supported yet.

### ISSUE THREAD

**Issue by messaddek** [WarningImHack3r/intellij-shadcn-plugin#59]
### What is the issue?

I pulled a project from github (my project) and i got the error message: Multiple Project Detected, not supported yet.

### What are the steps to reproduce this issue?

Project Pulled

### What were you expecting to happen?

Current shadcn components

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi, is your project a monorepo containing multiple projects each having their own package.json file?

**Comment by messaddek** [comment]
Hello, yes, indeed i has a package.json which i am not using. thanks

**Comment by WarningImHack3r** [comment]
Alright closing this then :)
